chore: upgrade go to 1.19
Otel core collector requires 1.19/ Otherwise, the build is failing with:

```
Error: ../../../../go/pkg/mod/go.opentelemetry.io/collector/featuregate@v0.73.0/gate.go:27:25: undefined: atomic.Bool
Error: ../../../../go/pkg/mod/go.opentelemetry.io/collector/featuregate@v0.73.0/registry.go:93:23: undefined: atomic.Bool
Error: ../../../../go/pkg/mod/go.opentelemetry.io/collector/featuregate@v0.73.0/registry.go:95:22: undefined: atomic.Bool
```